import { StyleSheet, View } from "react-native";

export const memegen = {
    'X,X Everywhere' : 'buzz',
    '10 Guy' : 'tenguy',
    'Afraid to Ask Andy' : 'afraid',
    'Almost Politically Correct Redneck' : 'apcr',
    'An Older Code Sir, But It Checks Out' : 'older',
    'Ancient Aliens Guy' : 'aag',
    'And Then I Said' : 'atis',
    'At Least You Tried' : 'tried',
    'Insanity Wolf' : 'iw',
    'Baby Insanity Wolf' : 'biw',
    'Baby, You\'ve Got a Stew Going' : 'stew',
    'Bad Luck Brian' : 'blb',
    'But That\'s None of My Business' : 'kermit',
    'Butthurt Dweller' : 'bd',
    'Captain Hindsight' : 'ch',
    'Comic Book Guy' : 'cbg',
    'Condescending Wonka' : 'wonka',
    'Confession Bear' : 'cb',
    'Confused Gandalf' : 'gandalf',
    'Conspiracy Keanu' : 'keanu',
    'Crying on Floor' : 'cryingfloor',
    'Dating Site Murderer' : 'dsm',
    'Disaster Girl' : 'disastergirl',
    'Do It Live!' : 'live',
    'Do You Want Ants?' : 'ants',
    'Doge' : 'doge',
    'Donald Trump' : 'trump',
    'Drakeposting' : 'drake',
    'Ermahgerd' : 'ermg',
    'Facepalm' : 'facepalm',
    'First Try!' : 'firsttry',
    'First World Problems' : 'fwp',
    'Forever Alone' : 'fa',
    'Foul Bachelor Frog' : 'fbf',
    'Fuck Me, Right?' : 'fmr',
    'Futurama Fry' : 'fry',
    'Good Guy Greg' : 'ggg',
    'Grumpy Cat' : 'grumpy Cat',
    'Hide the Pain Harold' : 'harold',
    'Hipster Barista' : 'hipster',
    'I Feel Like I am Taking Crazy Pills' : 'crazypills',
    'I Guarantee It' : 'mw',
    'I Have No Idea What I am Doing' : 'noidea',
    'I Immediately Regret This Decision!' : 'regret',
    'I Should Buy a Boat Cat' : 'boat',
    'I Should Not Have Said That' : 'hagrid',
    'I Would Be So Happy' : 'sohappy',
    'I am the Captain Now' : 'captain',
    'I am Going to Build My Own Theme Park' : 'bender',
    'Inigo Montoya' : 'inigo',
    'It is A Trap!' : 'ackbar',
    'Its Happening' : 'happening',
    'Its Simple, Kill the Batman' : 'joker',
    'Jony Ive Redesigns Things' : 'ive',
    'Laughing Lizard' : 'll',
    'Laundry Room Viking' : 'lrv',
    'Leo Strutting' : 'leo',
    'Life... Finds a Way' : 'away',
    'Matrix Morpheus' : 'morpheus',
    'Member Berries' : 'mb',
    'Milk Was a Bad Choice' : 'badchoice',
    'Minor Mistake Marvin' : 'mmm',
    'Mocking Spongebob' : 'spongebob',
    'Oh, Is That What We are Going to Do Today?' : 'red',
    'One Does Not Simply Walk into Mordor' : 'mordor',
    'Oprah You Get a Car' : 'oprah',
    'Overly Attached Girlfriend' : 'oag',
    'Pepperidge Farm Remembers' : 'remembers',
    'Persian Cat Room Guardian' : 'persian',
    'Philosoraptor' : 'philosoraptor',
    'Push it somewhere else Patrick' : 'patrick',
    'Roll Safe' : 'rollsafe',
    'Sad Barack Obama' : 'sad-obama',
    'Sad Bill Clinton' : 'sad-clinton',
    'Sad Frog / Feels Bad Man' : 'sadfrog',
    'Sad George Bush' : 'sad-bush',
    'Sad Joe Biden' : 'sad-biden',
    'Sad John Boehner' : 'sad-boehner',
    'Salt Bae' : 'saltbae',
    'Scumbag Brain' : 'sb',
    'Scumbag Steve' : 'ss',
    'Seal of Approval' : 'soa',
    'Sealed Fate' : 'sf',
    'See? Nobody Cares' : 'dodgson',
    'Shut Up and Take My Money!' : 'money',
    'Skeptical Third World Kid' : 'sk',
    'Socially Awkward Penguin' : 'awkward',
    'Socially Awesome Penguin' : 'awesome',
    'Stop It, Get Some Help' : 'stop-it',
    'Success Kid' : 'success',
    'Sudden Clarity Clarence' : 'scc',
    'Super Cool Ski Instructor' : 'ski',
    'Sweet Brown / Ain\'t Nobody Got Time For That' : 'aint-got-time',
    'That Would Be Great' : 'officespace',
    'The Most Interesting Man in the World' : 'interesting',
    'The Rent Is Too Damn High' : 'toohigh',
    'This is Bull, Shark' : 'bs',
    'This is Sparta!' : 'sparta',
    'Winter is coming' : 'winter',
    'X all the Y' : 'xy',
    'Y U NO Guy' : 'yuno',
    'You Were the Chosen One!' : 'chosen',




}